name: test-build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '^1.19.0' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Go setup
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.node-version }}

      - name: Print version
        run: go version

      - name: Test - Coverage
        run: go test ./... -cover

      - name: Test - Race conditions
        run: go test ./... -race

      - name: Build
        run: go build -o 'exec' .
